version: '3'

services:
  docs:
    build: .
    image: karkas
    volumes:
      - .:/usr/src/app
    command: nimble docs

  book:
    build: .
    image: karkas
    volumes:
      - .:/usr/src/app
    command: nimble book

